### ISSUE TITLE
zzlibx264 does not find nasm

### ISSUE THREAD

**Issue by andrey-bat** [innerlee/setup#11]
Hi,

I've run upon the following issue:

./zzlibx264.sh
libx264 will be installed in /root/app
downloads/libx264.tar.gz exist
Found no assembler
Minimum version is nasm-2.13
If you really want to compile without asm, configure with --disable-asm.

Nasm was installed into /root/app by zznasm, zzlibx265 sees and uses it.

Environment: docker container from tensorflow/tensorflow:latest-gpu-jupyter

**Comment by innerlee** [comment]
Hi, are the env variables exported?

![image](https://user-images.githubusercontent.com/9464825/89747304-c926f080-daf0-11ea-961c-5620dc2b84a4.png)

**Comment by andrey-bat** [comment]
Oh, really. I missed some of these. Thanks!
Now I got to zzopencv and it failed...

**Comment by zfhxi** [comment]
I also met this problem, I solve it by adding env variables NASM, YASM, AS:
```
#!/bin/zsh
# install libx264
set -e

ROOTDIR=${ZZROOT:-$HOME/app}
NAME="libx264"
TYPE=".tar.gz"
FILE="$NAME$TYPE"
DOWNLOADURL="https://code.videolan.org/videolan/x264/-/archive/master/x264-master.tar.gz"
echo $NAME will be installed in "$ROOTDIR"

mkdir -p "$ROOTDIR/downloads"
cd "$ROOTDIR"

if [ -f "downloads/$FILE" ]; then
    echo "downloads/$FILE exist"
else
    echo "$FILE does not exist, downloading from $DOWNLOADURL"
    wget $DOWNLOADURL -O $FILE
    mv $FILE downloads/
fi

mkdir -p src/$NAME
tar xf downloads/$FILE -C src/$NAME --strip-components 1
cd src/$NAME

export PKG_CONFIG_PATH="$ROOTDIR/lib/pkgconfig:$ROOTDIR/share/pkgconfig:"$PKG_CONFIG_PATH
+ export NASM="/opt/opencv4.4.0-cuda/app/bin/nasm"
+ export YASM="/opt/opencv4.4.0-cuda/app/bin/yasm"
+ export AS="${NASM}"

./configure --prefix="$ROOTDIR" --enable-shared
make -j"$(nproc)" && make install

echo $NAME installed on "$ROOTDIR"
```
from https://stackoverflow.com/questions/44572813/building-x264-with-yasm-failing-the-asm-check
