### ISSUE TITLE
Link in zzlibx265.sh has failed

### ISSUE THREAD

**Issue by xwen99** [innerlee/setup#12]
This link: https://bitbucket.org/multicoreware/x265/downloads/x265_3.2.1.tar.gz

**Comment by innerlee** [comment]
oh, thanks!

**Comment by innerlee** [comment]
could you check this link http://anduin.linuxfromscratch.org/BLFS/x265/x265_3.4.tar.gz from http://www.linuxfromscratch.org/blfs/view/svn/multimedia/x265.html?

**Comment by xwen99** [comment]
Great, things worked smoothly with libx265.
Still, "ERROR: x265 not found using pkg-config" occurred while running `zzffmpeg.sh`, solved by installing pkg-config from conda.
Now things work fine, thanks a lot!

**Comment by innerlee** [comment]
thanks for the feedback!
