### ISSUE TITLE
gcc 6.1 corresponding gmp, mpfr, mpc version

### ISSUE THREAD

**Issue by ShoufaChen** [innerlee/setup#25]
Hi,

If I want to install gcc 6.1, how can I determine the corresponding gmp, mpfr, mpc version?

Thanks in advance.

**Comment by innerlee** [comment]
by asking google :p http://ftp.oregonstate.edu/.2/lfs-website/lfs/view/development/chapter05/gcc-pass1.html

**Comment by ShoufaChen** [comment]
Thanks.
