### ISSUE TITLE
zzopencv.sh fail with no sys/videoio.h

### ISSUE THREAD

**Issue by gddingcs** [innerlee/setup#27]
these are the outputs from the terminal 

> ../../../../lib/libopencv_core.so.4.3.0: undefined reference to `cv::error(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, char const*, int)'
> collect2: error: ld returned 1 exit status
> modules/xobjdetect/tools/waldboost_detector/CMakeFiles/opencv_waldboost_detector.dir/build.make:105: recipe for target 'bin/opencv_waldboost_detector' failed
> make[2]: *** [bin/opencv_waldboost_detector] Error 1
> CMakeFiles/Makefile2:4811: recipe for target 'modules/xobjdetect/tools/waldboost_detector/CMakeFiles/opencv_waldboost_detector.dir/all' failed
> make[1]: *** [modules/xobjdetect/tools/waldboost_detector/CMakeFiles/opencv_waldboost_detector.dir/all] Error 2
> Makefile:162: recipe for target 'all' failed
> make: *** [all] Error 

this is from the CMakeError.log

> Determining if the include file sys/videoio.h exists failed with the following output:
> Change Dir: /home/xxxxx/app/src/opencv/build/CMakeFiles/CMakeTmp
> Run Build Command:"/usr/bin/make" "cmTC_54d50/fast"
> /usr/bin/make -f CMakeFiles/cmTC_54d50.dir/build.make CMakeFiles/cmTC_54d50.dir/build
> make[1]: Entering directory '/home/xxxxxx/app/src/opencv/build/CMakeFiles/CMakeTmp'
> Building C object CMakeFiles/cmTC_54d50.dir/CheckIncludeFile.c.o
> /usr/bin/cc   -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wuninitialized -Winit-self -Wno-comment -Wno-missing-field-initializers -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden  -O3 -DNDEBUG  -DNDEBUG -fPIE   -o CMakeFiles/cmTC_54d50.dir/CheckIncludeFile.c.o   -c /home/xxxxxx/app/src/opencv/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
> /home/xxxxx/app/src/opencv/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:10: fatal error: sys/videoio.h: No such file or directory
>  #include <sys/videoio.h>
>           ^~~~~~~~~~~~~~~
> compilation terminated.
> CMakeFiles/cmTC_54d50.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_54d50.dir/CheckIncludeFile.c.o' failed
> make[1]: *** [CMakeFiles/cmTC_54d50.dir/CheckIncludeFile.c.o] Error 1
> make[1]: Leaving directory '/home/dinggd/app/src/opencv/build/CMakeFiles/CMakeTmp'
> Makefile:126: recipe for target 'cmTC_54d50/fast' failed
> make: *** [cmTC_54d50/fast] Error 2

Seems like no `sys/videoio.h` is the main cause of this fail, can you throw some lights on it?

Thanks,

**Comment by gddingcs** [comment]
gcc version 7.5
cuda 10.2
ubuntu 18.04

if any further system info needed, please let me know, thanks again.

**Comment by innerlee** [comment]
It seen to be a gcc version problem. Which version are you using?

**Comment by innerlee** [comment]
Hmm no, could you try to add some options on the command https://github.com/innerlee/setup/blob/master/zzopencv.sh#L85 ?
Something like `-DWITH_V4L=OFF -DWITH_LIBV4L=ON`

**Comment by innerlee** [comment]
If the above option does not work, try this `-DINSTALL_C_EXAMPLES=OFF`

**Comment by gddingcs** [comment]
I have removed previous files and started from scratch after each option change. seems like the problem remains the same, nothing has changed.

**Comment by innerlee** [comment]
Is the folder `~/app/src/opencv/build` deleted?

**Comment by gddingcs** [comment]
> Is the folder `~/app/src/opencv/build` deleted?

Yes and I actually removed opencv folder completely.

And I am closing this issue as I have successfully installed denseflow with another server with exact same config, this problem no longer appears, so my system can be somehow corrupted. 

Thanks again for your prompt relay and this great work.
