### ISSUE TITLE
OpenCV version in zzopencv.sh will fail compilation in CUDA 11.0 or later

### ISSUE THREAD

**Issue by xieshuqin** [innerlee/setup#29]
Hi,

I tried to follow zzopencv.sh to install OpenCV with CUDA but ran into the bugs listed below. 
[Stackoverflow: Build OpenCV-4.0.0 with cuda 11 on Ubuntu 18.04](https://stackoverflow.com/questions/62297025/build-opencv-4-0-0-with-cuda-11-on-ubuntu-18-04)

Changing the OpenCV version to 4.4.0 fixes the problem, as mentioned here. 
[zero2smthg' answer](https://stackoverflow.com/a/65229365)

I think the opencv version in zzopencv.sh can be updated to 4.4.0 to fix this problem.

**Comment by innerlee** [comment]
Thanks! Would you mind making a pull request?

**Comment by xieshuqin** [comment]
The fix is simple. 

Modify `zzopencv.sh` line 11 - 12: 
```
DOWNLOADURL1="https://github.com/opencv/opencv/archive/4.3.0.tar.gz"
DOWNLOADURL2="https://github.com/opencv/opencv_contrib/archive/4.3.0.tar.gz"
```
to 
```
DOWNLOADURL1="https://github.com/opencv/opencv/archive/4.4.0.tar.gz"
DOWNLOADURL2="https://github.com/opencv/opencv_contrib/archive/4.4.0.tar.gz"
```
Then problem solved.
