### ISSUE TITLE
cmake: command not found

### ISSUE THREAD

**Issue by onlyonewater** [innerlee/setup#31]
when I use the command: `./zzopencv.sh`, I get an error: CMake: command not found, but I am sure I installed the CMake by using command `./zzcmake.sh`, and it was installed successfully. So what's wrong?

**Comment by innerlee** [comment]
The cmake is installed in `~/app/bin`, so make sure this path is in `PATH`

**Comment by innerlee** [comment]
see https://github.com/innerlee/setup#usage

**Comment by onlyonewater** [comment]
oh, thanks! I have a question, Do I need to add the path every time when I use the command, or just need to add the path for the first time?

**Comment by innerlee** [comment]
You can put them at `.bashrc`, then it will be run automatically each time the shell is loaded.

**Comment by onlyonewater** [comment]
oh, I get it, thanks!!
