### ISSUE TITLE
403 Forbidden when downloading boost.tar

### ISSUE THREAD

**Issue by rlleshi** [innerlee/setup#32]
@[zzboost](https://github.com/innerlee/setup/blob/master/zzboost.sh) the current download URL is inaccessible. 

Perhaps `DOWNLOADURL="https://boostorg.jfrog.io/artifactory/main/release/1.73.0/source/boost_1_73_0.tar.gz"`  would be better?

**Comment by innerlee** [comment]
Thanks! I will change it

**Comment by innerlee** [comment]
done
