### ISSUE TITLE
opencv gets installed, but module not found in python

### ISSUE THREAD

**Issue by antbertrand** [innerlee/setup#34]
Hi,

I'm setting up an environment to work with the MMAction2 library. And I wanted to use your build of opencv as it seems to be optimized for the use of denseflow. However, when I use the script `./zzopencv.sh`, everything runs great, I then added the export that is specified at the end to my bashrc, sourced it, but the module cv2 can't be found in python3. 
I noticed I could import it in python2, so I thought the problem came from this [line](https://github.com/innerlee/setup/blob/master/zzopencv.sh#L82), as I don't have any alias linking python to python3. I changed it, rebuild everything but I still have the same problem.
Any ideas of what is happening ? Did I miss anything ?

Thanks in advance for your help,

**Comment by antbertrand** [comment]
And also, I did export the $ZZROOT/bin to my $PATH

**Comment by innerlee** [comment]
This setup does not build the python binding. Pls modify the cmake options for your need. https://github.com/innerlee/setup/blob/master/zzopencv.sh#L78-L82

**Comment by antbertrand** [comment]
Oh, thx, I managed to bind it to my python but by manually adding the install path to my PYTHONPATH.  `export PYTHONPATH=$ZZROOT/lib/python3.6/dist-packages:$PYTHONPATH` in the bashrc.
I tried to use the cmake options, but I guess I couldn't find the correct configuration.
Thanks anyway !
