### ISSUE TITLE
zzdenseflow.sh error after dependencies are successfully installed

### ISSUE THREAD

**Issue by caposerenity** [innerlee/setup#43]
Hi, I'm trying to install denseflow with this guide [link](https://github.com/open-mmlab/denseflow/blob/master/INSTALL.md), aftering successfully installing opencv and boost, I still fail to install denseflow

The log info of installing opencv and denseflow are shown below
[log_denseflow.txt](https://github.com/innerlee/setup/files/8499488/log_denseflow.txt)
[log_opencv.txt](https://github.com/innerlee/setup/files/8499489/log_opencv.txt)

**Comment by yyccli** [comment]
你好，我得到了类似的报错，在尝试build denseflow的时候。不过我相较于你少了关于GLIBCXX类似的错误，我想那个可能和你使用的GCC版本有关，我使用9.2.0的版本时不存在这些错误。但是关于opencv链接的问题仍然存在，也仍在排查问题qwq

**Comment by yyccli** [comment]
最终解决了这个问题，关键应该在于opencv的库目录链接上，即denseflow目录下的CMakeLists.txt中关于库目录的设置。希望能帮助到你
