### ISSUE TITLE
Error in zzboost.sh!

### ISSUE THREAD

**Issue by sjtuytc** [innerlee/setup#9]
the name of downloaded file should be boost_1_71_0.tar.gz
therefore, line 24 should be 
`tar xf downloads/boost_1_71_0.tar.gz -C src/$NAME --strip-components 1`

**Comment by innerlee** [comment]
hi, what's the printed error message in terminal?

**Comment by sjtuytc** [comment]
the original line 24 is tar xf downloads/boost.tar.gz -C src/$NAME --strip-components 1
I thought it cannot find boost.tar.gz

**Comment by innerlee** [comment]
maybe, does it actually errors?

**Comment by sjtuytc** [comment]
class.cpp:(.text+0x30): undefined reference to `string_new(string*)'

**Comment by sjtuytc** [comment]
Building Boost.Build engine with toolset gcc...

Failed to build Boost.Build build engine
Consult 'bootstrap.log' for more details

In bootstrap.log,
g++ -x c++ -std=c++11 -O2 -s -DNDEBUG builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp execcmd.cpp filesys.cpp frames.cpp function.cpp glob.cpp hash.cpp hcache.cpp hdrmacro.cpp headers.cpp jam.cpp jambase.cpp jamgram.cpp lists.cpp make.cpp make1.cpp md5.cpp mem.cpp modules.cpp native.cpp object.cpp option.cpp output.cpp parse.cpp pathsys.cpp regexp.cpp rules.cpp scan.cpp search.cpp strings.cpp subst.cpp sysinfo.cpp timestamp.cpp variable.cpp w32_getreg.cpp modules/order.cpp modules/path.cpp modules/property-set.cpp modules/regex.cpp modules/sequence.cpp modules/set.cpp execunix.cpp fileunix.cpp pathunix.cpp -o b2
debugger.cpp: In function ‘void debug_mi_format_breakpoint(int)’:
debugger.cpp:1837:16: warning: zero-length gnu_printf format string [-Wformat-zero-length]
     printf( "" );
                ^
debugger.cpp: In function ‘LIST* debug_list_read(FILE*)’:
debugger.cpp:165:11: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
     fscanf( in, "%d", &len );
     ~~~~~~^~~~~~~~~~~~~~~~~~
/tmp/cchPy2pm.o: In function `class_module_name(_object*)':
class.cpp:(.text+0x30): undefined reference to `string_new(string*)'
class.cpp:(.text+0x3f): undefined reference to `string_append(string*, char const*)'
class.cpp:(.text+0x4a): undefined reference to `string_append(string*, char const*)'
class.cpp:(.text+0x5e): undefined reference to `string_free(string*)'
/tmp/cchPy2pm.o: In function `import_base_rule(void*, void*)':
class.cpp:(.text+0xb9): undefined reference to `string_new(string*)'
class.cpp:(.text+0xc5): undefined reference to `string_append(string*, char const*)'
class.cpp:(.text+0xd2): undefined reference to `string_push_back(string*, char)'
class.cpp:(.text+0xdd): undefined reference to `string_append(string*, char const*)'
class.cpp:(.text+0xf1): undefined reference to `string_free(string*)'
/tmp/ccxAoogj.o: In function `make_absolute_path(_object*)':
debugger.cpp:(.text+0x7a1): undefined reference to `string_new(string*)'
debugger.cpp:(.text+0x7c0): undefined reference to `string_free(string*)'
/tmp/ccxAoogj.o: In function `get_filename(_object*)':
debugger.cpp:(.text+0x83c): undefined reference to `string_new(string*)'
debugger.cpp:(.text+0x85b): undefined reference to `string_free(string*)'
/tmp/ccxAoogj.o: In function `debug_object_read(_IO_FILE*)':

**Comment by innerlee** [comment]
Something to try:

* temporarily remove anaconda from PATH, and LD_LIBRARY_PATH
* rm src/boost.tar.gz and pull the setup repo and rerun ./zzboost.sh, I updated boost to 1.73.0 a few seconds ago.
* if the above does not work, could u report the gcc version?

**Comment by sjtuytc** [comment]
I solved it by clear the CPLUS_INCLUDE_PATH, following https://github.com/boostorg/build/issues/468.
I thought this problem is clear.

**Comment by innerlee** [comment]
glad you solved it. hope version 1.73.0 be smoother
